scala_sources(
    sources=['**/*.scala'],
    dependencies = [
        "src/main/scala/com/testingzone/infrastructure/kafka",
        "src/main/scala/com/testingzone/dependencies:kafka",
        "src/main/scala/com/testingzone/dependencies:cats-effect",
        "src/main/scala/com/testingzone/dependencies:tapir-server",
    ]
)