scala_sources(
    sources=['**/*.scala'],
    dependencies = [
        "src/main/scala/com/testingzone/infrastructure/kafka",
        "src/main/scala/com/testingzone/infrastructure/depends:kafka",
        "src/main/scala/com/testingzone/infrastructure/depends:cats-effect",
        "src/main/scala/com/testingzone/infrastructure/depends:tapir-server",
    ]
)